%{
=====================================================================
Propulsion function that takes Mach number and Altitude as input
and outputs the thrust available and TSFC data

Tabulates plain text files titled 00.txt through 30.txt
where 00 is Mach = 0.0 and 30 is Mach = 3.0

The directory where the plain text files exist must be specified as the
projdir argument

M is Mach number
h is altitude [meters]
Thrust_available [Newtons]
TSFC [1/hr]
---------------------------------------------------------------------
Written by: Rustin Faris
Written from:
Last Modified: 03/23/018
---------------------------------------------------------------------
%}
function [Thrust_available,TSFC] = Propulsion(M,h)
%--------------------------------------------------------------------------
% move to folder with propulsion data txt files:
current_folder = pwd; % save for moving back
projdir = sprintf('%s/%s/', pwd, 'propulsion data');
cd(projdir)
%--------------------------------------------------------------------------
Thrust = zeros(16,51);
TSFC = zeros(16,51);

for i = 1:16
    fnum = num2str((i-1)*2);
    if i<=5
        fnum = strcat('0',fnum);
    end
    filename = strcat(fnum,'.txt');
    try
    Untitled = importfile1(filename);
    catch continue
    end
    if length(Untitled(:,2))<51
        zerostoadd = 51-length(Untitled(:,2));
        addmatrix = zeros(zerostoadd,3);
        Untitled = [addmatrix;Untitled];
    end
    Thrust(i,:) = Untitled(:,2)';
    TSFC(i,:) = Untitled(:,3)';
end
h = h*3.28084; % [m]
Mach = [0:0.2:3]'; 
Alt = 0:2e3:100e3; % [m]
Thrust_available = interp2(Alt,Mach,Thrust,h,M)*4.44822;  % [Newtons]
TSFC = interp2(Alt,Mach,TSFC,h,M);  % [(lbm/hr)/lbf] = [1/hr]

%--------------------------------------------------------------------------
% move back to working folder:
cd(current_folder);
%--------------------------------------------------------------------------
end
%% ========================================================================
%IMPORTFILE1 Import numeric data from a text file as a matrix.
%   UNTITLED = IMPORTFILE1(FILENAME) Reads data from text file FILENAME for
%   the default selection.
%
%   UNTITLED = IMPORTFILE1(FILENAME, STARTROW, ENDROW) Reads data from rows
%   STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   Untitled = importfile1('00.txt', 2, 52);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/03/23 16:11:50
% =========================================================================
function Untitled = importfile1(filename, startRow, endRow)

if nargin<=2
    startRow = 2;
    endRow = inf;
end
%	column2: double (%f)
%   column3: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%8f%7f%7f%[^\n\r]';
fileID = fopen(filename,'r');
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

fclose(fileID);
Untitled = [dataArray{1:end-1}];
end